openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is the API documentation for the Contacts App.
tags:
  - name: Contacts
    description: Operations about contacts
  - name: Auth
    description: Authentication operations
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-ll11.onrender.com
paths:
  /contacts:
    $ref: ../swagger/paths/contacts/index.yaml
  /contacts/{contactId}:
    $ref: ../swagger/paths/contacts/{id}/index.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
